services:
  postgres:
    container_name: postgres_local
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=finance_dev
    restart: unless-stopped

volumes:
  postgres_data:
    name: postgres_finance_data
